excluded:
  - .build

disabled_rules:
  - opening_brace
  - blanket_disable_command
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - line_length
  - missing_docs
  - nesting
  - todo
  - type_body_length
  - type_name
  - identifier_name
  - large_tuple
  - unused_optional_binding
  - discarded_notification_center_observer
  - unused_closure_parameter
  - operator_whitespace
  - multiple_closures_with_trailing_closure
  - shorthand_operator
  - weak_delegate
  - void_function_in_ternary
opt_in_rules:
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - first_where
  - implicit_return
  - joined_default_parameter
  - no_extension_access_modifier
  - overridden_super_call
  - redundant_nil_coalescing
  - syntactic_sugar
  - toggle_bool

switch_case_alignment:
  indented_cases: true
